### PR TITLE
Only show proposal tags if they exist

### LINKED ISSUE #28: "Tags" selector is visible even if no tags are available
It leads to odd output when you click the dropdown and a sneaking suspicion that the request misbehaved or you (the talk proposer) are doing something wrong.

Screenshot (in selected mode):

### PR DESCRIPTION
**Pull request by kevinburke**
Fixes #28

### CODE REVIEW

**Comment by mghaught** [comment]
Hi Kevin,

I'll get some time this week to review and merge in your PRs.  One note, we've been working on a railsconf2015 branch with a lot of changes.  I can't be 100% if any of your fixes have already been fixed there but you may want to work on that branch.  As soon as I've done some QA on that branch, I'll be merging it back into master for others to use.  Since we're making lots of changes for our latest CFP, I didn't want to hit master with them until I was sure they were not going to bring over any RailsConf specific stuff that doesn't belong in master.  Thanks!

**Comment by kevinburke** [comment]
Should I submit these same PR's against that branch?

**Comment by mghaught** [comment]
Yeah, that would be preferred, plus you can make sure it works well with the latest active branch.  Thanks!

**Comment by kevinburke** [comment]
Okay I opened #31

**Pull request closed without merging**
