### PR TITLE
Feature/deploy to heroku button

### PR DESCRIPTION
**Pull request by hannesfostie**
Considering the app was written with Heroku in mind I decided to add their Deploy To Heroku button. This initial version seems to work, but I didn't take a whole lot of time to improve the readme around it.

Suggestions are welcome.

P.S.: We're checking out the app for use at ArrrrCamp. If there's anything we need to know, feel free to get in touch :-)

### CODE REVIEW

**Comment by hannesfostie** [comment]
Just realized the SendGrid implementation doesn't yet work, checking out what needs done.

**Comment by hannesfostie** [comment]
Tested and seems to work. Yay!

**Comment by mghaught** [comment]
Hi Hannes,

We have made a lot of improvements in the RailsConf2015 branch.  Assuming I get some time, I'll be merging all that into master next week.  I still need to touch up the README and do some deeper testing but the new branch is so much better.  I don't see any issues with this PR but I'll need to check it out against that branch first.  Thanks for contributing!

**Comment by hannesfostie** [comment]
Ha, I probably should have looked at that first. I'll rebase it tomorrow and make a PR for that branch instead!

**Comment by hannesfostie** [comment]
Closing in favor of #41

**Pull request closed without merging**
